# Generated by Django 2.2.16 on 2023-02-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230213_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
